language: python
branches:
  only:
  - master
install:
- pip install pelican
- pip install ghp-import
- pip install markdown
script:
- make publish github
env:
  global:
    secure: CwZ+p4FGZj/xx81ZNkx8BQXItli904YLHvrSPuSd/YAXpeG6cUdObxwUHvQ7yp19/zfSHIPGQuZX0+4oI4q67MowxQC/dbTD7Emj08XpmuAiRfycrD2WY8gmwN2hKIKUDFPTQkUozJGNcbXDG2wCKZ/bQdxJdqWbjeb6TcVz574=
